const stats = [{
  Name: "David Pastrnak",
  Position: "RW",
  Goals: "48",
  Assists: "47",
  Points: "95",
}, {
  Name: "Brad Marchand",
  Position: "LW",
  Goals: "28",
  Assists: "59",
  Points: "87",
}, {
  Name: "Patrice Bergeron",
  Position: "C",
  Goals: "31",
  Assists: "25",
  Points: "56",
}, {
  Name: "Torey Krug",
  Position: "D",
  Goals: "9",
  Assists: "40",
  Points: "49",
}, {
  Name: "David Krejci",
  Position: "C",
  Goals: "13",
  Assists: "30",
  Points: "43",
}, {
  Name: "Charlie Coyle",
  Position: "C",
  Goals: "16",
  Assists: "21",
  Points: "37",
}, {
  Name: "Jake DeBrusk",
  Position: "LW",
  Goals: "19",
  Assists: "16",
  Points: "35",
}, {
  Name: "Charlie McAvoy",
  Position: "D",
  Goals: "5",
  Assists: "27",
  Points: "32",
}, {
  Name: "Sean Kuraly",
  Position: "C",
  Goals: "6",
  Assists: "17",
  Points: "23",
}, {
  Name: "Matt Grzelcyk",
  Position: "D",
  Goals: "4",
  Assists: "17",
  Points: "21",
}, {
  Name: "Anders Bjork",
  Position: "LW",
  Goals: "9",
  Assists: "10",
  Points: "19",
}, {
  Name: "Brandon Carlo",
  Position: "D",
  Goals: "4",
  Assists: "15",
  Points: "19",
}, {
  Name: "Zdeno Chara",
  Position: "D",
  Goals: "5",
  Assists: "9",
  Points: "14",
}, {
  Name: "Chris Wagner",
  Position: "RW",
  Goals: "6",
  Assists: "4",
  Points: "10",
}, {
  Name: "Joakim Nordstrom",
  Position: "C",
  Goals: "4",
  Assists: "3",
  Points: "7",
}, {
  Name: "Par Lindholm",
  Position: "C",
  Goals: "3",
  Assists: "3",
  Points: "6",
}, {
  Name: "John Moore",
  Position: "D",
  Goals: "2",
  Assists: "1",
  Points: "3",
}, {
  Name: "Connor Clifton",
  Position: "D",
  Goals: "2",
  Assists: "0",
  Points: "2",
}, {
  Name: "Jacob Lauzon",
  Position: "D",
  Goals: "1",
  Assists: "1",
  Points: "2",
}, {
  Name: "Nick Richie",
  Position: "LW",
  Goals: "1",
  Assists: "1",
  Points: "2",
}, {
  Name: "Ondrej Kase",
  Position: "RW",
  Goals: "0",
  Assists: "1",
  Points: "1",
}, {
  Name: "Anton Blidh",
  Position: "LW",
  Goals: "0",
  Assists: "0",
  Points: "0",
}]

module.exports = stats
